// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewNexus.Data.Postgres;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewNexus.Data.Postgres.Migrations
{
    [DbContext(typeof(NewNexusDbContext))]
    partial class NewNexusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewNexus.Domain.Security.SecurityModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NavigationGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SecurityModule", "security");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3cbcc9c0-20e1-4a71-a6d9-84cbcb4d18d9"),
                            Code = "ADMINISTRATION",
                            DisplayOrder = 1,
                            IsActive = true,
                            Label = "Administration",
                            NavigationGroup = "Administration"
                        },
                        new
                        {
                            Id = new Guid("f0ecf806-db04-4ca0-a28a-a4c6064d5ea4"),
                            Code = "CARTE_POINTS_CHARGEMENT_DECHARGEMENT",
                            DisplayOrder = 1,
                            IsActive = true,
                            Label = "Carte des points chargements/déchargements",
                            NavigationGroup = "Exploitation"
                        },
                        new
                        {
                            Id = new Guid("2b098a1c-f365-4061-af8a-d6607a1324dd"),
                            Code = "INDICATEURS_CONDUCTEURS",
                            DisplayOrder = 2,
                            IsActive = true,
                            Label = "Les indicateurs conducteurs",
                            NavigationGroup = "Exploitation"
                        },
                        new
                        {
                            Id = new Guid("98f300bb-99f5-4980-a4f8-ee75f9588ca2"),
                            Code = "INDICATEURS_TRACTEURS",
                            DisplayOrder = 3,
                            IsActive = true,
                            Label = "Les indicateurs des tracteurs",
                            NavigationGroup = "Exploitation"
                        },
                        new
                        {
                            Id = new Guid("e97cef7f-67c9-4604-8987-4061536742db"),
                            Code = "GESTION_CONTRAVENTIONS",
                            DisplayOrder = 1,
                            IsActive = true,
                            Label = "Gestion des contraventions",
                            NavigationGroup = "Gestion administrative"
                        });
                });

            modelBuilder.Entity("NewNexus.Domain.Security.SecurityProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemProfile")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SecurityProfile", "security");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87b15c32-a3be-4e6c-90ff-3d228e561740"),
                            Code = "INFORMATIQUE",
                            IsActive = true,
                            IsSystemProfile = true,
                            Label = "Informatique"
                        },
                        new
                        {
                            Id = new Guid("b605e430-08c7-4f27-ad1d-a6fc70336da5"),
                            Code = "DIRECTION",
                            IsActive = true,
                            IsSystemProfile = true,
                            Label = "Direction"
                        },
                        new
                        {
                            Id = new Guid("8fbc1d63-4c92-4efe-9b03-a2e96f2f7b16"),
                            Code = "EXPLOITATION",
                            IsActive = true,
                            IsSystemProfile = true,
                            Label = "Exploitation"
                        },
                        new
                        {
                            Id = new Guid("0094b3de-3992-49d0-b5ea-b2b97a7c5d71"),
                            Code = "ADMINISTRATIF",
                            IsActive = true,
                            IsSystemProfile = true,
                            Label = "Administratif"
                        });
                });

            modelBuilder.Entity("NewNexus.Domain.Security.SecurityProfileModuleRight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SecurityModuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SecurityProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SecurityModuleId");

                    b.HasIndex("SecurityProfileId", "SecurityModuleId")
                        .IsUnique();

                    b.ToTable("SecurityProfileModuleRight", "security");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb0d95f2-835f-041d-3626-b9e9451b0f99"),
                            AccessLevel = "Write",
                            SecurityModuleId = new Guid("3cbcc9c0-20e1-4a71-a6d9-84cbcb4d18d9"),
                            SecurityProfileId = new Guid("87b15c32-a3be-4e6c-90ff-3d228e561740")
                        },
                        new
                        {
                            Id = new Guid("6ecdb34d-c477-0868-1978-7d43dd31559b"),
                            AccessLevel = "Write",
                            SecurityModuleId = new Guid("e97cef7f-67c9-4604-8987-4061536742db"),
                            SecurityProfileId = new Guid("87b15c32-a3be-4e6c-90ff-3d228e561740")
                        },
                        new
                        {
                            Id = new Guid("775da434-78ba-02cc-3275-99e4881b49e4"),
                            AccessLevel = "Write",
                            SecurityModuleId = new Guid("f0ecf806-db04-4ca0-a28a-a4c6064d5ea4"),
                            SecurityProfileId = new Guid("87b15c32-a3be-4e6c-90ff-3d228e561740")
                        },
                        new
                        {
                            Id = new Guid("acb8d62e-50db-0e0d-3f75-eb42f445339d"),
                            AccessLevel = "Write",
                            SecurityModuleId = new Guid("2b098a1c-f365-4061-af8a-d6607a1324dd"),
                            SecurityProfileId = new Guid("87b15c32-a3be-4e6c-90ff-3d228e561740")
                        },
                        new
                        {
                            Id = new Guid("1f425c89-3a4b-07ec-3407-d357770e9be2"),
                            AccessLevel = "Write",
                            SecurityModuleId = new Guid("98f300bb-99f5-4980-a4f8-ee75f9588ca2"),
                            SecurityProfileId = new Guid("87b15c32-a3be-4e6c-90ff-3d228e561740")
                        },
                        new
                        {
                            Id = new Guid("8ab92df0-2826-0556-0bc4-2237bb7e757c"),
                            AccessLevel = "None",
                            SecurityModuleId = new Guid("3cbcc9c0-20e1-4a71-a6d9-84cbcb4d18d9"),
                            SecurityProfileId = new Guid("b605e430-08c7-4f27-ad1d-a6fc70336da5")
                        },
                        new
                        {
                            Id = new Guid("5f790b4f-6f0e-0923-249a-e69d23542f7e"),
                            AccessLevel = "Read",
                            SecurityModuleId = new Guid("e97cef7f-67c9-4604-8987-4061536742db"),
                            SecurityProfileId = new Guid("b605e430-08c7-4f27-ad1d-a6fc70336da5")
                        },
                        new
                        {
                            Id = new Guid("46e91c36-d3c3-0387-0f97-023a767e3301"),
                            AccessLevel = "Read",
                            SecurityModuleId = new Guid("f0ecf806-db04-4ca0-a28a-a4c6064d5ea4"),
                            SecurityProfileId = new Guid("b605e430-08c7-4f27-ad1d-a6fc70336da5")
                        },
                        new
                        {
                            Id = new Guid("9d0c6e2c-fba2-0f46-0297-709c0a204978"),
                            AccessLevel = "Read",
                            SecurityModuleId = new Guid("2b098a1c-f365-4061-af8a-d6607a1324dd"),
                            SecurityProfileId = new Guid("b605e430-08c7-4f27-ad1d-a6fc70336da5")
                        },
                        new
                        {
                            Id = new Guid("2ef6e48b-9132-06a7-09e5-4889896be107"),
                            AccessLevel = "Read",
                            SecurityModuleId = new Guid("98f300bb-99f5-4980-a4f8-ee75f9588ca2"),
                            SecurityProfileId = new Guid("b605e430-08c7-4f27-ad1d-a6fc70336da5")
                        },
                        new
                        {
                            Id = new Guid("7f50e565-9796-025e-3989-062f696225b2"),
                            AccessLevel = "Read",
                            SecurityModuleId = new Guid("f0ecf806-db04-4ca0-a28a-a4c6064d5ea4"),
                            SecurityProfileId = new Guid("8fbc1d63-4c92-4efe-9b03-a2e96f2f7b16")
                        },
                        new
                        {
                            Id = new Guid("a4b5977f-bff7-0e9f-3489-7489153c5fcb"),
                            AccessLevel = "Read",
                            SecurityModuleId = new Guid("2b098a1c-f365-4061-af8a-d6607a1324dd"),
                            SecurityProfileId = new Guid("8fbc1d63-4c92-4efe-9b03-a2e96f2f7b16")
                        },
                        new
                        {
                            Id = new Guid("174f1dd8-d567-077e-3ffb-4c9c9677f7b4"),
                            AccessLevel = "Read",
                            SecurityModuleId = new Guid("98f300bb-99f5-4980-a4f8-ee75f9588ca2"),
                            SecurityProfileId = new Guid("8fbc1d63-4c92-4efe-9b03-a2e96f2f7b16")
                        },
                        new
                        {
                            Id = new Guid("e9e85ca1-5e5b-0fd4-3c6d-f2d8291b1faa"),
                            AccessLevel = "Write",
                            SecurityModuleId = new Guid("e97cef7f-67c9-4604-8987-4061536742db"),
                            SecurityProfileId = new Guid("0094b3de-3992-49d0-b5ea-b2b97a7c5d71")
                        });
                });

            modelBuilder.Entity("NewNexus.Domain.Security.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmployeeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("SecurityProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("SecurityProfileId");

                    b.ToTable("UserAccount", "security");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f6f6d4b-a2af-4d74-9ab3-6b033463d6a1"),
                            CreatedAtUtc = new DateTime(2026, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Administrateur système",
                            IsActive = true,
                            Login = "admin",
                            MustChangePassword = true,
                            PasswordHash = "100000.T4PL0v0v1mGm2O8x2M8vMw==.xdyoWj/llsa9F5KoRoeZc8mUL29qNlCKh8LzHxzd8MM=",
                            SecurityProfileId = new Guid("87b15c32-a3be-4e6c-90ff-3d228e561740")
                        });
                });

            modelBuilder.Entity("NewNexus.Domain.Security.SecurityProfileModuleRight", b =>
                {
                    b.HasOne("NewNexus.Domain.Security.SecurityModule", "SecurityModule")
                        .WithMany("ProfileRights")
                        .HasForeignKey("SecurityModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewNexus.Domain.Security.SecurityProfile", "SecurityProfile")
                        .WithMany("ModuleRights")
                        .HasForeignKey("SecurityProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityModule");

                    b.Navigation("SecurityProfile");
                });

            modelBuilder.Entity("NewNexus.Domain.Security.UserAccount", b =>
                {
                    b.HasOne("NewNexus.Domain.Security.SecurityProfile", "SecurityProfile")
                        .WithMany("UserAccounts")
                        .HasForeignKey("SecurityProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SecurityProfile");
                });

            modelBuilder.Entity("NewNexus.Domain.Security.SecurityModule", b =>
                {
                    b.Navigation("ProfileRights");
                });

            modelBuilder.Entity("NewNexus.Domain.Security.SecurityProfile", b =>
                {
                    b.Navigation("ModuleRights");

                    b.Navigation("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
